### ISSUE TITLE
Add support to Nano Id

### ISSUE THREAD

**Issue by YousefAK009** [Lippur/StrictId#3]
Hi, thank you for this library

is there a way to add custom IDs, I want to use NanoId
https://github.com/codeyu/nanoid-net

**Comment by Lippur** [comment]
Hi, glad you like the library!
Is there any particular reason why you need NanoIds? They seem to be a much less common, less standardised, and less performant alternative to Ulid, while doing essentially the same thing. 
I find it highly beneficial that Ulid, which the library currently uses, is convertible to Guid, which means it can be stored in UUID columns in databases and processed as GUID/UUID in external applications if a user finds that useful or necessary. Ulid is also very performant, and easy to read - subjectively more so than NanoId. 

I don't mind creating alternative ID types in the future, but I would probably not see NanoId as one of the first priorities. Unless there's a very compelling reason?

**Comment by YousefAK009** [comment]
I am already using Ulid as the primary key, so I was thinking it's a good idea to use nano id, but thanks to you, now I will stick to Ulid 

and about your question:
> Is there any particular reason why you need NanoIds?

I can use it to generate random Shortcuts URLs or  any Random short Otp because  it's very secure and you can handle the size and the alphabet that can be used

https://github.com/ai/nanoid?tab=readme-ov-file#custom-alphabet-or-size
https://zelark.github.io/nano-id-cc/

so after your clarification, I will use nano id as an external library, and no need to be added to the Strict ID library
